name: Azure Python 3.7
on: [push]
jobs:
    bulid:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  cd ch1
                  make install
            - name: Lint
              run: |
                  cd ch1  
                  make lint
            - name: Test
              run: |
                  cd ch1
                  make test
